// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.
/* eslint-disable @typescript-eslint/no-explicit-any, @typescript-eslint/no-empty-function, @typescript-eslint/no-unused-vars */

/** user-defined commands **/

export const commands = {
  async listRepos(): Promise<Result<Repo[], AppError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('list_repos') };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  async addRepo(path: string): Promise<Result<Repo, AppError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('add_repo', { path }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  async listBranches(repoPath: string): Promise<Result<string[], AppError>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('list_branches', { repoPath }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  async createWorkspace(
    repoId: string,
    baseBranch: string,
    taskText: string,
  ): Promise<Result<Workspace, AppError>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('create_workspace', {
          repoId,
          baseBranch,
          taskText,
        }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  async listWorkspaces(): Promise<Result<Workspace[], AppError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('list_workspaces') };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  async listTasks(repoId: string): Promise<Result<Task[], AppError>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('list_tasks', { repoId }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  async archiveWorkspace(workspaceId: string): Promise<Result<null, AppError>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('archive_workspace', { workspaceId }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  async startAgentRun(
    workspaceId: string,
    prompt: string,
    onEvent: TAURI_CHANNEL<StreamEvent>,
  ): Promise<Result<AgentRun, AppError>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('start_agent_run', {
          workspaceId,
          prompt,
          onEvent,
        }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  async stopAgentRun(runId: string): Promise<Result<null, AppError>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('stop_agent_run', { runId }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  async listRuns(workspaceId: string): Promise<Result<AgentRun[], AppError>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('list_runs', { workspaceId }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  async getWorkspaceDiff(
    workspaceId: string,
  ): Promise<Result<WorkspaceChange | null, AppError>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('get_workspace_diff', { workspaceId }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  /**
   * "Undo the last agent run." Resets the worktree to the most-recent
   * `agent_runs.checkpoint_sha` for this workspace's thread. Only the
   * latest run's diff is reverted; earlier-run diffs that were never
   * committed upstream stay in the worktree. With no prior run that
   * captured a checkpoint, returns `AppError::Validation` (UI shows a
   * friendly "nothing to discard" toast). For the v0.0.1 single-decision
   * flow (one run per archive/discard cycle) this matches the user's
   * mental model.
   */
  async discardWorkspaceChanges(
    workspaceId: string,
  ): Promise<Result<null, AppError>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('discard_workspace_changes', { workspaceId }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  async checkClaudeInstall(): Promise<ClaudeInstall> {
    return await TAURI_INVOKE('check_claude_install');
  },
};

/** user-defined events **/

export const events = __makeEvents__<{
  agentRunTerminated: AgentRunTerminated;
}>({
  agentRunTerminated: 'agent-run-terminated',
});

/** user-defined constants **/

/** user-defined types **/

export type AgentRun = {
  run_id: string;
  thread_id: string;
  prompt: string;
  status: string;
  started_at: number;
  ended_at: number | null;
  exit_code: number | null;
  error_message: string | null;
  checkpoint_sha: string | null;
};
/**
 * Fired once per `agent_runs` row when the supervisor task reaches a
 * terminal status (`done`, `error`, `stopped`, `crashed`). Front-end
 * consumers filter by `run_id` to learn when the channel stream is
 * safe to complete (Q2 — no polling).
 *
 * This is the **only** tauri-specta event in v0.0.1. The Rust crate
 * emits via `tauri_specta::Event::emit` on the `AppHandle`; the
 * Angular `_bindings.ts` surfaces it as `events.agentRunTerminated`.
 */
export type AgentRunTerminated = { run_id: string; status: string };
export type AppError =
  | { kind: 'Db'; message: string }
  | { kind: 'Io'; message: string }
  | { kind: 'NotFound'; message: string }
  | { kind: 'Validation'; message: string }
  | { kind: 'AgentSpawn'; message: string }
  | { kind: 'GitCmd'; message: string };
/**
 * Outcome of probing for the `claude` CLI.
 */
export type ClaudeInstall =
  | { kind: 'installed'; version: string }
  | { kind: 'missing' };
export type Repo = {
  repo_id: string;
  path: string;
  display_name: string;
  added_at: number;
};
export type StreamEvent =
  | { kind: 'stream_token'; text: string }
  /**
   * Declared for `agent_events.event_type` round-trip + Angular binding stability;
   * **not** emitted by `parse_line` in v0.0.1 (D1.4-A).
   */
  | { kind: 'tool_call'; name: string; args_json: string }
  | { kind: 'cli_output'; line: string }
  /**
   * Declared but **not** emitted by `parse_line` in v0.0.1 (D1.4-A).
   */
  | { kind: 'status_update'; status: string }
  | { kind: 'error'; message: string };
export type Task = {
  task_id: string;
  repo_id: string;
  title: string;
  task_text: string;
  status: string;
  created_at: number;
};
export type Thread = {
  thread_id: string;
  workspace_id: string;
  created_at: number;
};
export type Workspace = {
  workspace_id: string;
  task_id: string;
  worktree_path: string;
  branch_name: string;
  base_branch: string;
  status: string;
  created_at: number;
  deletion_intent: number;
};
export type WorkspaceChange = {
  change_id: number;
  workspace_id: string;
  run_id: string | null;
  diff_text: string;
  files_added: number;
  files_modified: number;
  files_deleted: number;
  captured_at: number;
};

/** tauri-specta globals **/

import {
  invoke as TAURI_INVOKE,
  Channel as TAURI_CHANNEL,
} from '@tauri-apps/api/core';
import * as TAURI_API_EVENT from '@tauri-apps/api/event';
import { type WebviewWindow as __WebviewWindow__ } from '@tauri-apps/api/webviewWindow';

type __EventObj__<T> = {
  listen: (
    cb: TAURI_API_EVENT.EventCallback<T>,
  ) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
  once: (
    cb: TAURI_API_EVENT.EventCallback<T>,
  ) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
  emit: null extends T
    ? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
    : (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
  | { status: 'ok'; data: T }
  | { status: 'error'; error: E };

function __makeEvents__<T extends Record<string, any>>(
  mappings: Record<keyof T, string>,
) {
  return new Proxy(
    {} as unknown as {
      [K in keyof T]: __EventObj__<T[K]> & {
        (handle: __WebviewWindow__): __EventObj__<T[K]>;
      };
    },
    {
      get: (_, event) => {
        const name = mappings[event as keyof T];

        return new Proxy((() => {}) as any, {
          apply: (_, __, [window]: [__WebviewWindow__]) => ({
            listen: (arg: any) => window.listen(name, arg),
            once: (arg: any) => window.once(name, arg),
            emit: (arg: any) => window.emit(name, arg),
          }),
          get: (_, command: keyof __EventObj__<any>) => {
            switch (command) {
              case 'listen':
                return (arg: any) => TAURI_API_EVENT.listen(name, arg);
              case 'once':
                return (arg: any) => TAURI_API_EVENT.once(name, arg);
              case 'emit':
                return (arg: any) => TAURI_API_EVENT.emit(name, arg);
            }
          },
        });
      },
    },
  );
}
