import type { AuthSessionDto } from '../../../core/_bindings';
import type { AuthSession } from './auth.model';

// Mappers between the Rust wire shape (`expires_at: number`,
// auto-generated by tauri-specta) and the domain model (Date object).
// The wire DTO type itself is imported from `_bindings.ts` — no
// duplicate hand-written shape.

export function sessionFromDto(dto: AuthSessionDto): AuthSession {
  return {
    token: dto.token,
    expiresAt: new Date(dto.expires_at),
  };
}

export function sessionToDto(session: AuthSession): AuthSessionDto {
  return {
    token: session.token,
    expires_at: session.expiresAt.getTime(),
  };
}
