pub mod bindings_export;
pub mod branch_name;
pub mod claude_cli;
pub mod commands;
pub mod credentials;
pub mod db;
pub mod error;
pub mod file_diff;
pub mod file_tree;
pub mod file_watcher_registry;
pub mod git_query;
pub mod ide_launch;
pub mod run_registry;
pub mod sandbox;
pub mod terminal;
pub mod terminal_registry;
pub mod workspace_run_registry;
pub mod workspace_service;
pub mod worktree;

#[cfg(test)]
mod spikes;

use std::path::PathBuf;
use tauri::Manager;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    // Build the typed surface. `tauri_specta::Builder` in v2.0.0-rc.21 is
    // not `Clone`, so we construct two independent instances from the same
    // factory: one consumed by `.invoke_handler`, one moved into `.setup`
    // for `mount_events`. The single `build_specta_builder()` definition
    // keeps the command/type list in one place.
    let specta_builder = bindings_export::build_specta_builder();

    // Debug-only: regenerate the typed TS bindings from the source of
    // truth. Release builds never write to the source tree.
    //
    // `bigint(Number)` is required because `db::models::*` carries
    // `i64` Unix-millisecond timestamps (`started_at`, `created_at`,
    // ...). specta's default policy is `BigIntForbidden`, which would
    // panic on first debug boot. Mozart's actual i64 values (Unix-ms
    // timestamps ~1.7e12, exit codes 0-255, small file counts) all fit
    // safely within JS Number precision (2^53), so `Number` is chosen
    // over `BigInt` for ergonomics: `new Date(workspace.created_at)`
    // and `if (run.exit_code === 0)` work without bigint coercion.
    #[cfg(debug_assertions)]
    {
        const BINDINGS_PATH: &str = "../src/app/core/_bindings.ts";
        specta_builder
            .export(
                specta_typescript::Typescript::default()
                    .bigint(specta_typescript::BigIntExportBehavior::Number)
                    .formatter(specta_typescript::formatter::prettier),
                BINDINGS_PATH,
            )
            .expect("tauri-specta export failed");

        // Post-export shim: tauri-specta v2.0.0-rc.21 emits a self-colliding
        // `export type TAURI_CHANNEL<TSend> = null;` alongside its own
        // `import { Channel as TAURI_CHANNEL }` line, causing TS2440 in
        // strict-mode Angular builds. It also emits `: any` casts in the
        // error envelope which violate `@typescript-eslint/no-explicit-any`
        // and an empty `__makeEvents__` factory which violates
        // `no-empty-function` / `no-unused-vars`. Both issues are upstream
        // generator quirks. Strip the colliding alias + inject a header
        // that disables the matching eslint rules for this generated file.
        // Idempotent: re-running the shim on an already-clean file is a no-op.
        let raw = std::fs::read_to_string(BINDINGS_PATH).expect("read bindings");
        let stripped: String = raw
            .lines()
            .filter(|l| !l.trim_start().starts_with("export type TAURI_CHANNEL"))
            .collect::<Vec<_>>()
            .join("\n");
        let header = "/* eslint-disable @typescript-eslint/no-explicit-any, \
                      @typescript-eslint/no-empty-function, \
                      @typescript-eslint/no-unused-vars */";
        let final_content = if stripped.contains("eslint-disable") {
            stripped
        } else {
            // Insert header on line 2 (after the leading `// This file was
            // generated by [tauri-specta]…` comment).
            let mut lines = stripped.lines();
            let first = lines.next().unwrap_or("");
            let rest: Vec<&str> = lines.collect();
            let mut out = String::with_capacity(stripped.len() + header.len() + 2);
            out.push_str(first);
            out.push('\n');
            out.push_str(header);
            out.push('\n');
            out.push_str(&rest.join("\n"));
            out
        };
        // Ensure trailing newline (lost during the line-by-line rebuild).
        let with_newline = if final_content.ends_with('\n') {
            final_content
        } else {
            format!("{final_content}\n")
        };
        std::fs::write(BINDINGS_PATH, with_newline).expect("rewrite bindings");
    }

    let setup_builder = bindings_export::build_specta_builder();

    tauri::Builder::default()
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_notification::init())
        .invoke_handler(specta_builder.invoke_handler())
        .setup(move |app| {
            // Preserve the debug-only log plugin from the pre-1.7 lib.rs.
            if cfg!(debug_assertions) {
                app.handle().plugin(
                    tauri_plugin_log::Builder::default()
                        .level(log::LevelFilter::Info)
                        .build(),
                )?;
            }

            // DB path: env override > app_data_dir/mozart.db
            let db_path: PathBuf = std::env::var_os("MOZART_DB_PATH")
                .map(PathBuf::from)
                .unwrap_or_else(|| {
                    let dir = app
                        .path()
                        .app_data_dir()
                        .expect("app_data_dir unresolvable");
                    std::fs::create_dir_all(&dir).ok();
                    dir.join("mozart.db")
                });
            let db_state = db::init_db(&db_path).expect("db init failed");
            app.manage(db_state);

            // Run registry holds live RunHandles for stop_agent_run lookup.
            app.manage(run_registry::RunRegistry::new());

            // File-watcher registry holds notify-debouncer handles keyed
            // by workspace_id (Phase 4b). Atom C registers the
            // skeleton; Atom E populates it from `watch_repository_tree`.
            app.manage(file_watcher_registry::FileWatcherRegistry::new());

            // Terminal registry holds PTY handles keyed by workspace_id
            // (Phase 4d). One PTY per workspace, killed on archive.
            app.manage(terminal_registry::TerminalRegistry::new());

            // Run registry holds PTY handles for the project's run
            // command, also keyed by workspace_id (Phase 4e). Killed
            // on archive.
            app.manage(workspace_run_registry::WorkspaceRunRegistry::new());

            // Typed event mounting: no-op for v0.0.1 (no events declared
            // yet) but forward-compatible — future Builder.events() calls
            // register here.
            setup_builder.mount_events(app);

            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
