pub mod auth;
pub mod bindings_export;
pub mod branch_name;
pub mod claude_cli;
pub mod commands;
pub mod commit;
pub mod credentials;
pub mod db;
pub mod error;
pub mod file_diff;
pub mod file_tree;
pub mod file_tree_cache;
pub mod file_watcher_registry;
pub mod get_started;
pub mod git_query;
pub mod github;
pub mod ide_launch;
pub mod merge;
pub mod mozart_config;
pub mod path_guard;
pub mod paths;
pub mod run_registry;
pub mod sandbox;
pub mod settings;
pub mod sound;
pub mod staging;
pub mod terminal;
pub mod terminal_registry;
pub mod workspace_run_registry;
pub mod workspace_service;
pub mod worktree;

#[cfg(test)]
mod spikes;

use std::path::PathBuf;
use tauri::Manager;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    // Build the typed surface. `tauri_specta::Builder` in v2.0.0-rc.21 is
    // not `Clone`, so we construct two independent instances from the same
    // factory: one consumed by `.invoke_handler`, one moved into `.setup`
    // for `mount_events`. The single `build_specta_builder()` definition
    // keeps the command/type list in one place.
    let specta_builder = bindings_export::build_specta_builder();

    // Debug-only: regenerate the typed TS bindings from the source of
    // truth. Release builds never write to the source tree.
    //
    // `bigint(Number)` is required because `db::models::*` carries
    // `i64` Unix-millisecond timestamps (`started_at`, `created_at`,
    // ...). specta's default policy is `BigIntForbidden`, which would
    // panic on first debug boot. Mozart's actual i64 values (Unix-ms
    // timestamps ~1.7e12, exit codes 0-255, small file counts) all fit
    // safely within JS Number precision (2^53), so `Number` is chosen
    // over `BigInt` for ergonomics: `new Date(workspace.created_at)`
    // and `if (run.exit_code === 0)` work without bigint coercion.
    #[cfg(debug_assertions)]
    {
        const BINDINGS_PATH: &str = "../src/app/core/_bindings.ts";
        specta_builder
            .export(
                specta_typescript::Typescript::default()
                    .bigint(specta_typescript::BigIntExportBehavior::Number)
                    .formatter(specta_typescript::formatter::prettier),
                BINDINGS_PATH,
            )
            .expect("tauri-specta export failed");

        // Post-export shim: tauri-specta v2.0.0-rc.21 emits a self-colliding
        // `export type TAURI_CHANNEL<TSend> = null;` alongside its own
        // `import { Channel as TAURI_CHANNEL }` line, causing TS2440 in
        // strict-mode Angular builds. It also emits `: any` casts in the
        // error envelope which violate `@typescript-eslint/no-explicit-any`
        // and an empty `__makeEvents__` factory which violates
        // `no-empty-function` / `no-unused-vars`. Both issues are upstream
        // generator quirks. Strip the colliding alias + inject a header
        // that disables the matching eslint rules for this generated file.
        // Idempotent: re-running the shim on an already-clean file is a no-op.
        let raw = std::fs::read_to_string(BINDINGS_PATH).expect("read bindings");
        let stripped: String = raw
            .lines()
            .filter(|l| !l.trim_start().starts_with("export type TAURI_CHANNEL"))
            .collect::<Vec<_>>()
            .join("\n");
        let header = "/* eslint-disable @typescript-eslint/no-explicit-any, \
                      @typescript-eslint/no-empty-function, \
                      @typescript-eslint/no-unused-vars */";
        let final_content = if stripped.contains("eslint-disable") {
            stripped
        } else {
            // Insert header on line 2 (after the leading `// This file was
            // generated by [tauri-specta]…` comment).
            let mut lines = stripped.lines();
            let first = lines.next().unwrap_or("");
            let rest: Vec<&str> = lines.collect();
            let mut out = String::with_capacity(stripped.len() + header.len() + 2);
            out.push_str(first);
            out.push('\n');
            out.push_str(header);
            out.push('\n');
            out.push_str(&rest.join("\n"));
            out
        };
        // Ensure trailing newline (lost during the line-by-line rebuild).
        let with_newline = if final_content.ends_with('\n') {
            final_content
        } else {
            format!("{final_content}\n")
        };
        std::fs::write(BINDINGS_PATH, with_newline).expect("rewrite bindings");
    }

    let setup_builder = bindings_export::build_specta_builder();

    tauri::Builder::default()
        // Single-instance MUST be the first plugin so a second
        // invocation (e.g. xdg-open of mozart://...) can be detected
        // before the rest of the app initializes. The deep-link feature
        // flag wires this to `tauri-plugin-deep-link`, so URLs forwarded
        // from the second instance fire `on_open_url` on the running
        // window. The callback brings the existing window to focus.
        .plugin(tauri_plugin_single_instance::init(|app, _argv, _cwd| {
            use tauri::Manager;
            if let Some(window) = app.get_webview_window("main") {
                let _ = window.unminimize();
                let _ = window.set_focus();
            }
        }))
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_notification::init())
        .plugin(tauri_plugin_deep_link::init())
        .plugin(tauri_plugin_shell::init())
        // Auto-updater (beta.1+). The plugin reads `plugins.updater`
        // from tauri.conf.json (endpoints + pubkey) — no Rust config
        // needed here. The matching `tauri-plugin-process` exposes
        // `relaunch()` to JS so the UpdaterService can restart after
        // installing the new bundle.
        .plugin(tauri_plugin_updater::Builder::new().build())
        .plugin(tauri_plugin_process::init())
        .invoke_handler(specta_builder.invoke_handler())
        .setup(move |app| {
            // Preserve the debug-only log plugin from the pre-1.7 lib.rs.
            if cfg!(debug_assertions) {
                app.handle().plugin(
                    tauri_plugin_log::Builder::default()
                        .level(log::LevelFilter::Info)
                        .build(),
                )?;
            }

            // DB path resolved by the central `paths` module (OS-standard
            // app-data dir, or the `MOZART_DB_PATH` override).
            let db_path = crate::paths::db_path().expect("db path unresolvable");
            if let Some(parent) = db_path.parent() {
                std::fs::create_dir_all(parent).ok();
            }
            let db_state = db::init_db(&db_path).expect("db init failed");

            // CG-2 — flip any workspace whose worktree has a lingering
            // `MERGE_HEAD` (app crash / power loss mid-merge) into the
            // `'conflict'` status so the standard resolve-in-IDE flow
            // takes over on this boot. Best-effort: missing worktrees
            // or git failures are logged and skipped — they will fail
            // later through their normal user-visible paths.
            recover_interrupted_merges(&db_state);

            app.manage(db_state);

            // Run registry holds live RunHandles for stop_agent_run lookup.
            app.manage(run_registry::RunRegistry::new());

            // File-watcher registry holds notify-debouncer handles keyed
            // by workspace_id (Phase 4b). Atom C registers the
            // skeleton; Atom E populates it from `watch_repository_tree`.
            app.manage(file_watcher_registry::FileWatcherRegistry::new());

            // File-tree cache keyed by workspace_id. Populated on the
            // first `list_repository_tree` per workspace and invalidated
            // by `spawn_watcher`'s debounce callback. Lets repeat
            // workspace visits skip the FS walk + git status.
            //
            // Wrapped in `Arc` because the watcher debouncer closure
            // captures it by move and runs on a background thread —
            // the same Arc is cloned into each watcher and into every
            // command call.
            app.manage(std::sync::Arc::new(file_tree_cache::FileTreeCache::new()));

            // Terminal registry holds PTY handles keyed by workspace_id
            // (Phase 4d). One PTY per workspace, killed on archive.
            app.manage(terminal_registry::TerminalRegistry::new());

            // Run registry holds PTY handles for the project's run
            // command, also keyed by workspace_id (Phase 4e). Killed
            // on archive.
            app.manage(workspace_run_registry::WorkspaceRunRegistry::new());

            // Typed event mounting : the specta builder owns the typed
            // event registry on the Rust side. Must run before any
            // `Event::emit` call (otherwise the listener machinery isn't
            // wired and emissions are silently dropped).
            setup_builder.mount_events(app);

            // Phase 5 / Atom 2 : register the mozart:// deep-link
            // handler now that the plugin is initialized and the typed
            // event registry is mounted.
            auth::deep_link::register(app.handle());

            // Phase 5 follow-up : start the localhost HTTP callback
            // server. Browsers on Linux silently drop the mozart://
            // launch from a webpage click ; the HTTP endpoint bypasses
            // the scheme handler entirely. apps/web fetches
            // 127.0.0.1:<port>/auth — the server synthesizes a
            // mozart:// URL and emits the same DeepLinkReceived event.
            let port = auth::http_callback::start_server(app.handle().clone());
            app.manage(auth::http_callback::CallbackPort(port));

            // Runtime window icon. `bundle.icon` in tauri.conf.json only
            // applies to the packaged build (.AppImage / .deb / .app /
            // .exe); in `tauri dev`, and for non-installed AppImage runs,
            // the dock/taskbar falls back to a generic GTK icon unless
            // the icon is set on the window at runtime. `include_bytes!`
            // embeds the PNG into the binary at compile time, sourced
            // directly from the `mozart-assets` lib.
            if let Some(window) = app.get_webview_window("main") {
                if let Ok(icon) = tauri::image::Image::from_bytes(include_bytes!(
                    "../../../libs/mozart-assets/src/desktop/app-icons/128x128.png"
                )) {
                    let _ = window.set_icon(icon);
                }
            }

            // Linux/WebKitGTK scroll-feel parity with Chromium. The
            // default WebKit "smooth scrolling" animates each wheel
            // tick, which feels noticeably slower than Chromium's
            // discrete wheel scroll for high-velocity mice. Disabling
            // smooth scrolling + forcing GPU compositing brings the
            // wheel feel close to Chromium on the same hardware. No-op
            // on macOS / Windows where Tauri's webview is native
            // WebKit / WebView2 with their own scroll defaults.
            #[cfg(target_os = "linux")]
            if let Some(window) = app.get_webview_window("main") {
                configure_webkit_scroll(&window);
            }

            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

/// Apply WebKitGTK scroll tweaks to bring wheel-scroll feel closer to
/// Chromium's on the same hardware. Called from the setup hook on
/// Linux only. Best-effort: any failure inside `with_webview` is
/// logged and ignored — the app still runs with WebKit defaults.
#[cfg(target_os = "linux")]
fn configure_webkit_scroll(window: &tauri::WebviewWindow) {
    use webkit2gtk::{SettingsExt, WebViewExt};
    if let Err(err) = window.with_webview(|webview| {
        let wv = webview.inner();
        if let Some(settings) = wv.settings() {
            settings.set_enable_smooth_scrolling(false);
            settings.set_hardware_acceleration_policy(
                webkit2gtk::HardwareAccelerationPolicy::Always,
            );
        }
    }) {
        eprintln!("[webkit] configure_webkit_scroll failed: {err}");
    }
}

/// CG-2 — scan workspaces at boot and flip any whose worktree carries
/// a `MERGE_HEAD` (interrupted merge) into the `'conflict'` runtime
/// status. Best-effort and silent on errors: a missing worktree, an
/// unreadable repo, or a `git rev-parse` failure does not block boot.
/// The user will see the same red-badge / Open-in-IDE surface as a
/// fresh conflict (A2.6.D), and any subsequent merge attempts will
/// re-run the probe and stay accurate.
fn recover_interrupted_merges(db: &db::DbState) {
    let workspaces = {
        let conn = db.lock();
        match db::workspaces::list_all(&conn) {
            Ok(rows) => rows,
            Err(e) => {
                eprintln!("CG-2 boot scan: list_all failed: {e}");
                return;
            }
        }
    };
    let rt = match tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
    {
        Ok(rt) => rt,
        Err(e) => {
            eprintln!("CG-2 boot scan: tokio runtime build failed: {e}");
            return;
        }
    };
    for ws in workspaces {
        if ws.status == merge::STATUS_CONFLICT {
            continue;
        }
        let worktree = PathBuf::from(&ws.worktree_path);
        if !worktree.exists() {
            continue;
        }
        let probe = rt.block_on(merge::has_in_progress_merge(&worktree));
        match probe {
            Ok(true) => {
                let conn = db.lock();
                if let Err(e) = db::workspaces::update_status(
                    &conn,
                    &ws.workspace_id,
                    merge::STATUS_CONFLICT,
                ) {
                    eprintln!(
                        "CG-2 boot scan: failed to set conflict on ws {}: {e}",
                        ws.workspace_id
                    );
                }
            }
            Ok(false) => {}
            Err(e) => {
                eprintln!(
                    "CG-2 boot scan: probe failed for ws {} at {}: {e}",
                    ws.workspace_id,
                    worktree.display()
                );
            }
        }
    }
}
