
/* eslint-disable @typescript-eslint/no-explicit-any, @typescript-eslint/no-empty-function, @typescript-eslint/no-unused-vars */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async listRepos() : Promise<Result<Repo[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_repos") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addRepo(path: string) : Promise<Result<Repo, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_repo", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run `git init --initial-branch=main` + identity config + an initial
 * empty commit at `path` so the folder becomes a valid git repository
 * Mozart can register. Called by the frontend after the user confirms
 * the Initialize-project dialog (triggered when `add_repo` returns the
 * `NotARepo` validation error).
 */
async initRepo(path: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("init_repo", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Clone the git repository at `url` into `<dest_dir>/<name>`, where
 * `name` is derived from the URL (last `/`-segment, trailing `.git`
 * stripped). Creates `dest_dir` if it does not exist. Returns the
 * absolute path of the cloned folder so the frontend can hand it to
 * `add_repo` for registration.
 * 
 * Refuses `file://` URLs (only http/https/ssh-like remote URLs are
 * allowed). Refuses if `<dest_dir>/<name>` already exists — the user
 * should pick a different location or remove the existing folder.
 */
async cloneRepo(url: string, destDir: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clone_repo", { url, destDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create an empty directory `<parent>/<name>` for a fresh "Quick start"
 * project. Validates inputs, refuses if the target already exists, and
 * returns the canonicalised absolute path so the frontend can hand it
 * to the unified add-project flow (which will trigger `git init` next).
 */
async createProjectFolder(parent: string, name: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_project_folder", { parent, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Detect the package manager for `workspace_id`'s worktree and run
 * `<manager> install`. Used by the Phase 1 add-project flow to make
 * the freshly-cloned workspace immediately usable. Non-blocking
 * from the user's perspective: the frontend fires this without
 * awaiting and toasts the outcome.
 * 
 * Detection order: pnpm-lock.yaml -> yarn.lock -> package-lock.json
 * -> npm (default when package.json exists but no lockfile).
 */
async installWorkspacePackages(workspaceId: string) : Promise<Result<InstallResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_workspace_packages", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeRepo(repoId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_repo", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setRepoIcon(repoId: string, icon: string | null) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_repo_icon", { repoId, icon }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setRepoHidden(repoId: string, hidden: boolean) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_repo_hidden", { repoId, hidden }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Apply a complete project ordering. `ordered_ids[i]` gets
 * `sort_index = i`. The Angular store debounces drag bursts so this
 * fires once per drop, not per dragOver.
 */
async setRepoSort(orderedIds: string[]) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_repo_sort", { orderedIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listBranches(repoPath: string) : Promise<Result<string[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_branches", { repoPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createWorkspace(repoId: string, baseBranch: string, taskText: string, workspaceName: string) : Promise<Result<Workspace, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_workspace", { repoId, baseBranch, taskText, workspaceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listWorkspaces() : Promise<Result<Workspace[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_workspaces") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listTasks(repoId: string) : Promise<Result<Task[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_tasks", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async archiveWorkspace(workspaceId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("archive_workspace", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Rename the user-facing workspace title. Intentionally does NOT
 * touch `branch_name` — the branch is derived from the original
 * name at create time and never re-derived (vocabulary contract).
 */
async renameWorkspace(workspaceId: string, name: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_workspace", { workspaceId, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set the kanban-lane label. The backend does not validate the value
 * against an enum; the Angular side owns the closed-set of allowed
 * `UiWorkspaceStatus` strings.
 */
async setWorkspaceUiStatus(workspaceId: string, uiStatus: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_workspace_ui_status", { workspaceId, uiStatus }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setWorkspacePinned(workspaceId: string, pinned: boolean) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_workspace_pinned", { workspaceId, pinned }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setWorkspaceUnread(workspaceId: string, unread: boolean) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_workspace_unread", { workspaceId, unread }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startAgentRun(workspaceId: string, prompt: string, onEvent: TAURI_CHANNEL<StreamEvent>) : Promise<Result<AgentRun, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_agent_run", { workspaceId, prompt, onEvent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopAgentRun(runId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_agent_run", { runId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listRuns(workspaceId: string) : Promise<Result<AgentRun[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_runs", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWorkspaceDiff(workspaceId: string) : Promise<Result<WorkspaceChange | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_workspace_diff", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * "Undo the last agent run." Resets the worktree to the most-recent
 * `agent_runs.checkpoint_sha` for this workspace's thread. Only the
 * latest run's diff is reverted; earlier-run diffs that were never
 * committed upstream stay in the worktree. With no prior run that
 * captured a checkpoint, returns `AppError::Validation` (UI shows a
 * friendly "nothing to discard" toast). For the v0.0.1 single-decision
 * flow (one run per archive/discard cycle) this matches the user's
 * mental model.
 */
async discardWorkspaceChanges(workspaceId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("discard_workspace_changes", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listChats(workspaceId: string) : Promise<Result<Chat[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_chats", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * All open chats across every workspace, newest first. Backs the
 * Phase 1 sidebar "Chats" group.
 */
async listAllChats() : Promise<Result<Chat[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_all_chats") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createChat(workspaceId: string, title: string, llmId: string | null) : Promise<Result<Chat, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_chat", { workspaceId, title, llmId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renameChat(chatId: string, title: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_chat", { chatId, title }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async closeChat(chatId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_chat", { chatId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getActiveChat(workspaceId: string) : Promise<Result<string | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_active_chat", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setActiveChat(workspaceId: string, chatId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_active_chat", { workspaceId, chatId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateChatMode(chatId: string, mode: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_chat_mode", { chatId, mode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateChatEffort(chatId: string, effort: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_chat_effort", { chatId, effort }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateChatModel(chatId: string, llmId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_chat_model", { chatId, llmId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async markChatRead(chatId: string, messageId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mark_chat_read", { chatId, messageId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listMessages(chatId: string) : Promise<Result<Message[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_messages", { chatId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Inserts a message and returns the canonical row. Angular passes a
 * pre-generated `message_id` so optimistic UI can swap by ID without
 * a round-trip ambiguity.
 */
async insertMessage(messageId: string, chatId: string, role: string, content: string, mode: string | null, status: string, runId: string | null, timelineJson: string | null) : Promise<Result<Message, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("insert_message", { messageId, chatId, role, content, mode, status, runId, timelineJson }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateMessageContent(messageId: string, content: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_message_content", { messageId, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateMessageStatus(messageId: string, status: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_message_status", { messageId, status }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateMessageTimeline(messageId: string, timelineJson: string | null) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_message_timeline", { messageId, timelineJson }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkClaudeInstall() : Promise<ClaudeInstall> {
    return await TAURI_INVOKE("check_claude_install");
},
/**
 * Step 6d — heuristic probe for an existing `claude /login` session. The
 * frontend uses this to give Pro/Max users a single-click "Connect"
 * experience that bypasses the API-key dialog when their CLI is already
 * authenticated.
 */
async checkClaudeCodeSession() : Promise<boolean> {
    return await TAURI_INVOKE("check_claude_code_session");
},
/**
 * Step 6 — cheap presence check used by the frontend on app start to know
 * whether to render "Not connected" immediately or to kick off a probe.
 * Never returns the value of the key.
 */
async hasAnthropicKey() : Promise<Result<boolean, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("has_anthropic_key") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Step 6 — probe-then-persist. Only writes to the keyring when the probe
 * returns `Connected`. On `Invalid` / `NetworkError` the key is dropped at
 * the end of this function frame and never touches disk. The argument
 * `key` is the only place the value is ever passed by-value into Mozart
 * from the frontend.
 */
async connectAnthropic(key: string) : Promise<Result<ProbeResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("connect_anthropic", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Step 6 — idempotent removal of the stored key. Safe to call when no
 * entry exists.
 */
async disconnectAnthropic() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("disconnect_anthropic") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Step 6 — re-probe the currently stored key. Returns `Validation` when no
 * key is stored (the frontend gates this call on `has_anthropic_key()` so
 * the error path is only hit on misuse).
 */
async refreshAnthropicConnection() : Promise<Result<ProbeResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("refresh_anthropic_connection") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List the workspace's worktree contents as a nested file tree, with
 * per-file change badges (`A` / `M` / `D`) computed against the
 * workspace's `base_branch`.
 * 
 * `show_ignored=false` filters via `.gitignore` (ripgrep walker).
 * `show_ignored=true` walks everything except `.git/` and tags entries
 * with the `ignored` flag so the UI can mute them.
 */
async listRepositoryTree(workspaceId: string, showIgnored: boolean) : Promise<Result<FileNodeDto[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_repository_tree", { workspaceId, showIgnored }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Subscribe to FS-change events for the workspace's worktree. Spawns
 * a `notify-debouncer-mini` watcher (200ms window) and registers it
 * keyed by `workspace_id` so a subsequent call for the same workspace
 * replaces the previous watcher.
 */
async watchRepositoryTree(workspaceId: string, onEvent: TAURI_CHANNEL<FileTreeEvent>) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("watch_repository_tree", { workspaceId, onEvent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Cancel the active watcher for `workspace_id`, if any. No-op if the
 * workspace has no active watcher.
 */
async unwatchRepositoryTree(workspaceId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unwatch_repository_tree", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resolve the unified diff text for one file in a workspace, against
 * the workspace's `base_branch`. Working tree (incl. staged + unstaged)
 * vs. base. Untracked files surface as a synthesized "all-added" diff;
 * unchanged files return an empty string (caller renders "No changes.").
 */
async getFileDiff(workspaceId: string, path: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_file_diff", { workspaceId, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open (or replace) the PTY for a workspace, rooted at its worktree.
 * Streams `TerminalEvent` chunks through `on_event`. Replacement
 * semantics: any prior PTY for the same workspace is killed before
 * the new one spawns. The Angular `TerminalRegistry` guarantees one
 * call per workspace per app session in normal flow; the replacement
 * path is a safety net for hot-reload + error recovery.
 */
async openTerminal(workspaceId: string, cols: number, rows: number, onEvent: TAURI_CHANNEL<TerminalEvent>) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_terminal", { workspaceId, cols, rows, onEvent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Forward bytes (typed by the user via xterm.js) to the PTY's stdin.
 */
async writeTerminal(workspaceId: string, data: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_terminal", { workspaceId, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resize the PTY to match xterm.js' viewport. Called on container
 * resize (debounced front-end side).
 */
async resizeTerminal(workspaceId: string, cols: number, rows: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resize_terminal", { workspaceId, cols, rows }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Close the PTY (kill the child + drop the master). No-op if no PTY
 * is registered for the workspace.
 */
async closeTerminal(workspaceId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_terminal", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update the project's `run_command`. Pass `None` to clear it.
 */
async setRepoRunCommand(repoId: string, command: string | null) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_repo_run_command", { repoId, command }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Spawn the project's `run_command` in a PTY rooted at the workspace's
 * worktree. Streams output through `on_event`. Replaces any prior run
 * PTY for the same workspace (the previous run is killed). Returns
 * `Validation` if the project has no `run_command` set.
 */
async startWorkspaceRun(workspaceId: string, cols: number, rows: number, onEvent: TAURI_CHANNEL<TerminalEvent>) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_workspace_run", { workspaceId, cols, rows, onEvent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop the workspace's run (kill the child, drop the PTY).
 */
async stopWorkspaceRun(workspaceId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_workspace_run", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Probe `$PATH` for known IDE binaries. The list is ordered as in
 * `KNOWN_IDES`. Front-end uses this to filter the static
 * `OPEN_IN_TOOLS` array.
 */
async detectInstalledIdes() : Promise<Result<DetectedIde[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("detect_installed_ides") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Launch `id` (e.g. `"vscode"`, `"cursor"`, `"finder"`) against the
 * workspace's worktree. The path is resolved server-side from the
 * workspace_id; the front-end never sees it.
 */
async openInIde(workspaceId: string, ideId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_in_ide", { workspaceId, ideId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Flat list of changed files in the workspace's worktree. Powers the
 * commit dialog's checkbox list.
 */
async listChangedFiles(workspaceId: string) : Promise<Result<ChangedFile[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_changed_files", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stage `paths` and create a commit with `message`. Returns the new
 * commit's sha. Refuses on empty path list / empty message.
 */
async commitWorkspace(workspaceId: string, paths: string[], message: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("commit_workspace", { workspaceId, paths, message }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hasGithubToken() : Promise<Result<boolean, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("has_github_token") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Probe the token via `GET /user`; on success store it in the
 * keyring and return the resolved login. Failure leaves the keyring
 * untouched.
 */
async connectGithub(token: string) : Promise<Result<GithubProbeResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("connect_github", { token }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async disconnectGithub() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("disconnect_github") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Push the workspace's branch to `origin` (with `-u`) using the local
 * git binary. Resolves the origin URL via `git remote get-url origin`.
 * Surfaces `Validation` if no `origin` is set.
 */
async pushWorkspaceBranch(workspaceId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("push_workspace_branch", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Push the branch (idempotent) then create a PR via the GitHub REST
 * API. Requires a stored GitHub token; the project's origin must
 * resolve to `github.com/<owner>/<repo>`.
 */
async createWorkspacePr(workspaceId: string, title: string, body: string, draft: boolean) : Promise<Result<CreatedPr, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_workspace_pr", { workspaceId, title, body, draft }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
agentRunTerminated: AgentRunTerminated
}>({
agentRunTerminated: "agent-run-terminated"
})

/** user-defined constants **/



/** user-defined types **/

export type AgentRun = { run_id: string; thread_id: string; prompt: string; status: string; started_at: number; ended_at: number | null; exit_code: number | null; error_message: string | null; checkpoint_sha: string | null }
/**
 * Fired once per `agent_runs` row when the supervisor task reaches a
 * terminal status (`done`, `error`, `stopped`, `crashed`). Front-end
 * consumers filter by `run_id` to learn when the channel stream is
 * safe to complete (Q2 — no polling).
 * 
 * This is the **only** tauri-specta event in v0.0.1. The Rust crate
 * emits via `tauri_specta::Event::emit` on the `AppHandle`; the
 * Angular `_bindings.ts` surfaces it as `events.agentRunTerminated`.
 */
export type AgentRunTerminated = { run_id: string; status: string }
export type AppError = { kind: "Db"; message: string } | { kind: "Io"; message: string } | { kind: "NotFound"; message: string } | { kind: "Validation"; message: string } | { kind: "AgentSpawn"; message: string } | { kind: "GitCmd"; message: string }
export type ChangedFile = { path: string; 
/**
 * `"added" | "modified" | "deleted"`. Untracked files surface as
 * "added" so the dialog presents them uniformly.
 */
status: string }
export type Chat = { chat_id: string; workspace_id: string; title: string; llm_id: string | null; mode: string; effort: string; last_read_message_id: string | null; closed_at: number | null; created_at: number }
/**
 * Outcome of probing for the `claude` CLI.
 */
export type ClaudeInstall = { kind: "installed"; version: string } | { kind: "missing" }
/**
 * Outcome of `POST /repos/{owner}/{repo}/pulls`.
 */
export type CreatedPr = { number: number; html_url: string }
export type DetectedIde = { 
/**
 * Stable identifier (e.g. `"vscode"`).
 */
id: string; 
/**
 * Resolved absolute binary path (informational).
 */
binary_path: string }
/**
 * Wire shape consumed by the Angular `RepositoriesAdapter`. Names are
 * snake_case on the wire; the TS side maps to camelCase via
 * `fileNodeFromDto`.
 */
export type FileNodeDto = { 
/**
 * Workspace-relative path, forward-slash separated. Empty for the
 * (synthetic) root — never emitted: `list_tree` returns the root's
 * children directly.
 */
path: string; name: string; 
/**
 * `"file"` or `"directory"`.
 */
kind: string; 
/**
 * `"added" | "modified" | "deleted" | "unchanged"`.
 */
status: string; 
/**
 * True if the entry is matched by `.gitignore`. When
 * `show_ignored=false` the entry would not be emitted, so this is
 * false for every node returned in that mode.
 */
ignored: boolean; 
/**
 * `Some(children)` for directories (possibly empty). `None` for files.
 */
children: FileNodeDto[] | null }
/**
 * Wire event payload pushed by `watch_repository_tree`. v0.0.1 emits a
 * single variant — the front-end re-fetches on every ping.
 */
export type FileTreeEvent = { kind: "changed" }
/**
 * Result of a `GET /user` probe with the candidate token.
 */
export type GithubProbeResult = { kind: "ok"; login: string } | { kind: "unauthorized" } | { kind: "network"; message: string }
/**
 * Outcome of an attempt to install package-manager dependencies for a
 * workspace. `ran=false` means no `package.json` was found; the other
 * two flags describe what happened when we did try.
 */
export type InstallResult = { 
/**
 * Detected package manager. "none" when ran=false.
 */
manager: string; 
/**
 * True if a package.json was present and we attempted install.
 */
ran: boolean; 
/**
 * True iff the install command exited 0.
 */
success: boolean; 
/**
 * Stderr tail on failure (empty otherwise). Bounded so we don't
 * dump megabytes of npm output back to the UI.
 */
message: string }
export type Message = { message_id: string; chat_id: string; run_id: string | null; role: string; content: string; mode: string | null; status: string; timeline_json: string | null; created_at: number }
/**
 * Outcome of a probe call. Sent to the frontend via tauri-specta as a
 * tagged TS union `{ kind: 'connected' | 'invalid' | 'network_error' }`.
 */
export type ProbeResult = { kind: "connected" } | { kind: "invalid" } | { kind: "network_error" }
export type Repo = { repo_id: string; path: string; display_name: string; added_at: number; icon: string | null; hidden: boolean; sort_index: number; 
/**
 * Optional dev/run command (e.g. `pnpm dev`) Phase 4e's Run tab
 * invokes inside a workspace's worktree.
 */
run_command: string | null }
export type StreamEvent = { kind: "stream_token"; text: string } | 
/**
 * Declared for `agent_events.event_type` round-trip + Angular binding stability;
 * **not** emitted by `parse_line` in v0.0.1 (D1.4-A).
 */
{ kind: "tool_call"; name: string; args_json: string } | { kind: "cli_output"; line: string } | 
/**
 * Declared but **not** emitted by `parse_line` in v0.0.1 (D1.4-A).
 */
{ kind: "status_update"; status: string } | { kind: "error"; message: string }
export type Task = { task_id: string; repo_id: string; title: string; task_text: string; status: string; created_at: number }
/**
 * Wire event payload pushed by the reader thread to the front-end.
 */
export type TerminalEvent = 
/**
 * A chunk of UTF-8 stdout/stderr output.
 */
{ kind: "output"; data: string } | 
/**
 * The shell process exited (or the reader loop terminated).
 */
{ kind: "exited"; code: number }
export type Thread = { thread_id: string; workspace_id: string; created_at: number }
export type Workspace = { workspace_id: string; task_id: string; name: string; worktree_path: string; branch_name: string; base_branch: string; status: string; pinned: boolean; unread: boolean; created_at: number; deletion_intent: number; ui_status: string }
export type WorkspaceChange = { change_id: number; workspace_id: string; run_id: string | null; diff_text: string; files_added: number; files_modified: number; files_deleted: number; captured_at: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
