import type { AuthSession } from '@mozart/desktop-auth-util';

// Wire shape exchanged with the Tauri side. Declared locally so this
// lib has no inbound dep on apps/desktop/core/_bindings — the desktop
// app passes its Tauri-generated shape into the mappers and TypeScript
// structural typing closes the bridge.
export interface AuthSessionDto {
  readonly token: string;
  readonly expires_at: number;
}

// Mappers between the Rust wire shape (`expires_at: number`,
// auto-generated by tauri-specta) and the domain model (Date object).

export function sessionFromDto(dto: AuthSessionDto): AuthSession {
  return {
    token: dto.token,
    expiresAt: new Date(dto.expires_at),
  };
}

export function sessionToDto(session: AuthSession): AuthSessionDto {
  return {
    token: session.token,
    expires_at: session.expiresAt.getTime(),
  };
}
